[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.29"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 10000

remappings = [
    "webauthn-sol/=lib/webauthn-sol/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "FreshCryptoLib/=lib/webauthn-sol/lib/FreshCryptoLib/solidity/src/",
    "account-abstraction/=lib/account-abstraction/contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "solady/=lib/solady/src/",
]

[profile.default.metadata]
bytecode_hash = "none"
append_cbor = true
